FROM metabase/metabase:latest

ARG MB_DB_TYPE=mysql
ARG MYSQL_PASSWORD
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_DATABASE
ARG MYSQL_USER

ENV MB_DB_TYPE=${MB_DB_TYPE}
ENV MB_DB_DBNAME=${MYSQL_PASSWORD}
ENV MB_DB_PORT=${MYSQL_PORT}
ENV MB_DB_USER=${MYSQL_USER}
ENV MB_DB_PASS=${MYSQL_PASSWORD}
ENV MB_DB_HOST=${MYSQL_HOST}